# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\new.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# import ui_source
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Win_traffic(object):
    def setupUi(self, Win_traffic):
        Win_traffic.setObjectName("Win_traffic")
        Win_traffic.resize(1107, 868)
        Win_traffic.setStyleSheet("QString qstrStylesheet = \"background-color:rgb(43, 43, 255)\";\n"
                                  "ui.pushButton->setStyleSheet(qstrStylesheet);")
        self.frame = QtWidgets.QFrame(Win_traffic)
        self.frame.setGeometry(QtCore.QRect(880, 140, 201, 701))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        # self.frame.setStyleSheet("background-color:rgb(255, 0, 0)")

        # ---------------------------数据日志输入框--------------------------
        self.label_log = QtWidgets.QLabel(self.frame)
        self.label_log.setGeometry(QtCore.QRect(5, 160, 190, 420))
        font = QtGui.QFont()
        font.setWeight(12)
        font.setBold(True)
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_log.setFont(font)
        self.label_log.setText("数据日志")
        self.label_log.setObjectName("label")
        self.label_log.setStyleSheet("background-color:rgb(37,37,38);color:rgb(197,197,197)")
        self.label_log.setAlignment(Qt.AlignHCenter)

        self.data_log = QtWidgets.QTextEdit(self.frame)
        self.data_log.setGeometry(QtCore.QRect(9, 185, 182, 380))
        self.data_log.setStyleSheet("background-color:rgb(60,60,60);color:rgb(197,197,197)")

        # ---------------------------数据日志输入框--------------------------


        # ---------------------------图片 视频 摄像头模式按钮--------------------------
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 200, 50))
        font = QtGui.QFont()
        font.setBold(True)
        # font.setUnderline(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(
            "QPushButton{color:#00FFFF;border: 2px solid #00FFFF;border-radius:4px;background-color:#000000} ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 80, 200, 50))
        font = QtGui.QFont()
        font.setBold(True)
        # font.setUnderline(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(
            "QPushButton{color:#00FFFF;border: 2px solid #00FFFF;border-radius:4px;background-color:#000000}")
        self.pushButton_2.setObjectName("pushButton_2")
        # self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        # self.pushButton_3.setGeometry(QtCore.QRect(0, 160, 200, 50))
        # font = QtGui.QFont()
        # font.setBold(True)
        # # font.setUnderline(True)
        # font.setWeight(75)
        # font.setStrikeOut(False)
        # self.pushButton_3.setFont(font)
        # self.pushButton_3.setStyleSheet(
        #     "QPushButton{color:#00FFFF;border: 2px solid #00FFFF;border-radius:4px;background-color:#000000}")
        # self.pushButton_3.setObjectName("pushButton_3")

        # ---------------------------图片 视频 摄像头模式按钮--------------------------



        # ---------------------------切换页面--------------------------

        self.frame_2 = QtWidgets.QFrame(Win_traffic)
        self.frame_2.setGeometry(QtCore.QRect(10, 110, 900, 750))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        # self.frame_2.setStyleSheet("background-color:rgb(0, 255, 0)")



        
        self.show_picture_page = QtWidgets.QStackedWidget(self.frame_2)
        self.show_picture_page.setGeometry(QtCore.QRect(0, 0, 860, 720))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.show_picture_page.setFont(font)
        self.show_picture_page.setObjectName("show_picture_page")


        # ---------------------------切换页面--------------------------



        # ---------------------------图片模式页面--------------------------
        self.photo = QtWidgets.QWidget()
        self.photo.setObjectName("photo")

        self.label_page1 = QtWidgets.QLabel(self.photo)
        self.label_page1.setGeometry(QtCore.QRect(50, 30, 800, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.label_page1.setFont(font)
        self.label_page1.setText("Photo Here")
        self.label_page1.setObjectName("label")
        self.label_page1.setStyleSheet("border: 4px dashed #FFFFFF;color:white")
        self.label_page1.setAlignment(Qt.AlignCenter)

        # self.label_file = QtWidgets.QLabel(self.photo)
        # self.label_file.setGeometry(QtCore.QRect(50, 650, 500, 40))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(10)
        # self.label_file.setFont(font)
        # self.label_file.setText("文件目录：")
        # self.label_file.setObjectName("label")
        # self.label_file.setStyleSheet("border: 2px dashed #FFFF00;color:white")

        # self.lineEdit = QtWidgets.QLineEdit(self.photo)
        # self.lineEdit.setGeometry(QtCore.QRect(120, 655, 420, 30))
        # self.lineEdit.setObjectName("lineEdit")
        # self.lineEdit.setStyleSheet("background-color:rgb(60, 60, 60);color:white")
        # # self.label_path.setAlignment(Qt.AlignCenter)

        # self.open_pic_btn = QtWidgets.QPushButton(self.photo)
        # self.open_pic_btn.setGeometry(QtCore.QRect(580, 650, 120, 40))
        # font = QtGui.QFont()
        # font.setBold(True)
        # # font.setUnderline(True)
        # font.setWeight(75)
        # self.open_pic_btn.setFont(font)
        # self.open_pic_btn.setStyleSheet("QPushButton{color:#ffffff;border: 2px solid yellow;border-radius:4px;}")
        # self.open_pic_btn.setObjectName("pushButton_4")
        # self.pic_det_btn = QtWidgets.QPushButton(self.photo)
        # self.pic_det_btn.setGeometry(QtCore.QRect(730, 650, 120, 40))
        # font = QtGui.QFont()
        # font.setBold(True)
        # # font.setUnderline(True)
        # self.pic_det_btn.setFont(font)
        # self.pic_det_btn.setStyleSheet("QPushButton{color:#ffffff;border: 2px solid yellow;border-radius:4px;}")
        # self.pic_det_btn.setObjectName("pushButton_5")
        self.show_picture_page.addWidget(self.photo)
        # ---------------------------图片模式页面--------------------------


        # ---------------------------视频模式页面--------------------------
        self.videos = QtWidgets.QWidget()
        self.videos.setObjectName("videos")
        self.vid_img = QtWidgets.QLabel(self.videos)
        self.vid_img.setGeometry(QtCore.QRect(50, 30, 800, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.vid_img.setFont(font)
        self.vid_img.setText("Video Here")
        self.vid_img.setObjectName("vid_img")
        self.vid_img.setStyleSheet("border: 4px dashed #FFFFFF;color:white")
        self.vid_img.setAlignment(Qt.AlignCenter)

        self.mp4_detection_btn = QtWidgets.QPushButton(self.videos)
        self.mp4_detection_btn.setGeometry(QtCore.QRect(580, 650, 120, 40))
        font = QtGui.QFont()
        font.setBold(True)
        # font.setUnderline(True)
        font.setWeight(75)
        self.mp4_detection_btn.setFont(font)
        self.mp4_detection_btn.setStyleSheet("QPushButton{color:#ffffff;border: 2px solid yellow;border-radius:4px;}")
        self.mp4_detection_btn.setObjectName("mp4_detection_btn")
        self.vid_stop_btn = QtWidgets.QPushButton(self.videos)
        self.vid_stop_btn.setGeometry(QtCore.QRect(730, 650, 120, 40))
        font = QtGui.QFont()
        font.setBold(True)
        # font.setUnderline(True)
        font.setWeight(75)
        self.vid_stop_btn.setFont(font)
        self.vid_stop_btn.setStyleSheet("QPushButton{color:#ffffff;border: 2px solid yellow;border-radius:4px;}")
        self.vid_stop_btn.setObjectName("vid_stop_btn")

        self.label_file_2 = QtWidgets.QLabel(self.videos)
        self.label_file_2.setGeometry(QtCore.QRect(50, 650, 500, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_file_2.setFont(font)
        self.label_file_2.setText("文件目录：")
        self.label_file_2.setObjectName("label")
        self.label_file_2.setStyleSheet("border: 2px dashed #FFFF00;color:white")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.videos)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 655, 420, 30))
        self.lineEdit_2.setObjectName("lineEdit")
        self.lineEdit_2.setStyleSheet("background-color:rgb(60, 60, 60);color:white")

        self.show_picture_page.addWidget(self.videos)
        # ---------------------------视频模式页面--------------------------




        # ---------------------------摄像头模式页面--------------------------
        self.camera = QtWidgets.QWidget()
        self.camera.setObjectName("camera")

        self.cam_img = QtWidgets.QLabel(self.camera)
        self.cam_img.setGeometry(QtCore.QRect(50, 30, 800, 600))
        self.cam_img.setStyleSheet("background-color:rgb(234, 33, 155)")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.cam_img.setFont(font)
        self.cam_img.setText("Camera Here")
        self.cam_img.setObjectName("cam_img")
        self.cam_img.setStyleSheet("border: 4px dashed #FFFFFF;color:white")
        self.cam_img.setAlignment(Qt.AlignCenter)
        
        self.webcam_detection_btn = QtWidgets.QPushButton(self.camera)
        self.webcam_detection_btn.setGeometry(QtCore.QRect(580, 650, 120, 40))
        self.webcam_detection_btn.setBaseSize(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setBold(True)
        # font.setUnderline(True)
        font.setWeight(75)
        self.webcam_detection_btn.setFont(font)
        self.webcam_detection_btn.setStyleSheet("QPushButton{color:#ffffff;border: 2px solid yellow;border-radius:4px;}")
        self.webcam_detection_btn.setObjectName("webcam_detection_btn")
       

        self.vid_stop_btn_cma = QtWidgets.QPushButton(self.camera)
        self.vid_stop_btn_cma.setGeometry(QtCore.QRect(730, 650, 120, 40))
        font = QtGui.QFont()
        font.setBold(True)
        # font.setUnderline(True)
        font.setWeight(75)
        self.vid_stop_btn_cma.setFont(font)
        self.vid_stop_btn_cma.setStyleSheet("QPushButton{color:#ffffff;border: 2px solid yellow;border-radius:4px;}")
        self.vid_stop_btn_cma.setObjectName("vid_stop_btn_cma")

        # self.label_file_3 = QtWidgets.QLabel(self.camera)
        # self.label_file_3.setGeometry(QtCore.QRect(50, 650, 500, 40))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(10)
        # self.label_file_3.setFont(font)
        # self.label_file_3.setText("文件目录：")
        # self.label_file_3.setObjectName("label")
        # self.label_file_3.setStyleSheet("border: 2px dashed #FFFF00;color:white")

        # self.lineEdit_3 = QtWidgets.QLineEdit(self.camera)
        # self.lineEdit_3.setGeometry(QtCore.QRect(120, 655, 420, 30))
        # self.lineEdit_3.setObjectName("lineEdit")
        # self.lineEdit_3.setStyleSheet("background-color:rgb(60, 60, 60);color:white")



        self.show_picture_page.addWidget(self.camera)
        # ---------------------------摄像头模式页面--------------------------



        self.label_title = QtWidgets.QLabel(Win_traffic)
        self.label_title.setGeometry(QtCore.QRect(380, 40, 300, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        # font.setUnderline(True)
        font.setWeight(75)
        self.label_title.setFont(font)

        self.label_title.setStyleSheet("color:#FFFFFF")
        # self.label_title.setStyleSheet("Font{background-color:rgb(255, 255, 255);}")
        self.label_title.setObjectName("label_2")
        self.listView = QtWidgets.QListView(Win_traffic)
        self.listView.setGeometry(QtCore.QRect(-5, 1, 1121, 871))
        # self.listView.setStyleSheet(" \n""background-image: url(:/bg.png);")background-color:blue;
        self.listView.setStyleSheet("background-color:#1E1E1E")

        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.label_title.raise_()

        self.retranslateUi(Win_traffic)
        self.show_picture_page.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Win_traffic)

    def retranslateUi(self, Win_traffic):
        _translate = QtCore.QCoreApplication.translate
        Win_traffic.setWindowTitle(_translate("Win_traffic", "Form"))
        self.pushButton.setText(_translate("Win_traffic", "打开摄像监控"))
        self.pushButton_2.setText(_translate("Win_traffic", "关闭摄像头"))
        # self.pushButton_3.setText(_translate("Win_traffic", "摄像头模式"))
        # self.open_pic_btn.setText(_translate("Win_traffic", "打开图片"))
        # self.pic_det_btn.setText(_translate("Win_traffic", "开始检测"))
        # self.mp4_detection_btn.setText(_translate("Win_traffic", "视频文件检测"))
        # self.vid_stop_btn.setText(_translate("Win_traffic", "停止检测"))
        # self.webcam_detection_btn.setText(_translate("Win_traffic", "摄像头检测"))
        # self.vid_stop_btn_cma.setText(_translate("Win_traffic", "停止检测"))

        self.label_title.setText(_translate("Win_traffic", "智能人体监控"))
